### ISSUE TITLE
probably the wrong URL

### ISSUE THREAD

**Issue by jcw** [EtchedPixels/RC2014-ROM#1]
https://github.com/EtchedPixels/RC2014-ROM/blob/9097d5aee072bf6587ecee787fab5584777f3a6f/Simple80/system.asm#L31

My guess is that it should be this one: <http://www.cpm.z80.de/license.html>

**Comment by EtchedPixels** [comment]
That's the same text - not sure I understand ?

**Comment by jcw** [comment]
Yes, same text. That's how I found it. But that URL is confusing, it points to an unrelated website.
Anyway, no big deal :)
