### ISSUE TITLE
Compile 1802 roms

### ISSUE THREAD

**Issue by hjkit** [EtchedPixels/RC2014-ROM#3]
I tried to compile rom.s and test.s for running the RC2014-1802 emulator.
Here is the output from the make run
?ASxxxx-Error-<q> in line 1 of test.s
              <q> '1 	.abs'
              <q> missing or improper operators, terminators, or delimiters
?ASxxxx-Error-<oq> in line 2 of test.s
              <o> '2 	.org	0'
              <o> .org in REL area or directive / mnemonic error
              <q> missing or improper operators, terminators, or delimiters
?ASxxxx-Error-<q> in line 6 of test.s
              <q> '6 	phi	6'
              <q> missing or improper operators, terminators, or delimiters
?ASxxxx-Error-<q> in line 8 of test.s
              <q> '8 	plo	6'
              <q> missing or improper operators, terminators, or delimiters
?ASxxxx-Error-<q> in line 10 of test.s
              <q> '10 	plo	8'
              <q> missing or improper operators, terminators, or delimiters
?ASxxxx-Error-<q> in line 28 of test.s
              <q> '28 	dec	7'
              <q> missing or improper operators, terminators, or delimiters
?ASxxxx-Error-<q> in line 29 of test.s
              <q> '29 	glo	7'
              <q> missing or improper operators, terminators, or delimiters
?ASxxxx-Error-<q> in line 31 of test.s
              <q> '31 	dec	8'
              <q> missing or improper operators, terminators, or delimiters
?ASxxxx-Error-<q> in line 32 of test.s
              <q> '32 	glo	8'
              <q> missing or improper operators, terminators, or delimiters
?ASxxxx-Error-<q> in line 33 of test.s
              <q> '33 	str	6'
              <q> missing or improper operators, terminators, or delimiters
make: *** [Makefile:4: test] Fehler 2

I used the latest version of as1802
as1802 -v
ASxxxx Assembler V05.40  (RCA 1802 COSMAC)
BTW can you give me an example of tested options for the RC214-1802 ?

**Comment by EtchedPixels** [comment]
You want the assembler from my toolchain for that code (or to go add a lot of # characters and convert it)

https://github.com/EtchedPixels/CC6303

has the most recent versions of as1802 in it

"make -f Makefile.1802"

I've tested it with a flat memory card, with the 512K/512K card, CF adapter, SC129 (the 8bit I/O port card), 16x50 UART and 32K/32K RAM/ROM. It won't work with the Zilog peripherals but ought to work with most other stuff.

**Comment by hjkit** [comment]
Sorry,
but it did not work as you described.
As far as I can see there is no 1802 stuff in CC6303.
I modified rom.s and got it compiled with the latest as1802 version.

**Comment by EtchedPixels** [comment]
Its in CC6303/as68 - I need to figure out how to split the tools up better because the compiler is 6800 but the as/ld are rather more. Anyway so long as you have it working all is good.
